### ISSUE TITLE
hasFlash() and others are deprecated since version 2.1 and will be removed in 2.3. FlashBag is now used instead.

### ISSUE THREAD

**Issue by KoenDG** [dsyph3r/symblog#10]
Just copy-pasting what the debug toolbar is telling me. I'm using 2.2.2 right now.

The Changelog.md file says: 
    Deprecated the following methods from the Session class: `setFlash()`, `setFlashes()`, `getFlash()`, `hasFlash()`, and `removeFlash()`. Use `getFlashBag()` instead which returns a `FlashBagInterface`.

This is about the contact.html.twig file.

I updated to the following code in the following files:

contact.html.twig:
`{% if app.session.getFlashBag.has('blogger-notice') %}`

PageController.php:
`$this->get('session')->getFlashBag()->add('blogger-notice', 'Your contact enquiry was successfully sent. Thank you!');`

And I'm getting the flash message, just like it did with the deprecated functions.

**Comment by pchr-srf** [comment]
setFlash and the other deprecated methods do not work anymore in Symfony 2.7.12 and newer versions. I changed the code samples in Part 2 of the tutorial
