### ISSUE TITLE
Blogger\BlogBundle\DataFixtures\ORM\ issue

### ISSUE THREAD

**Issue by darrarski** [dsyph3r/symblog#4]
When I follow install instructions I'm getting this error after executing php app/console doctrine:fixtures:load

```
Fatal error: Declaration of Blogger\BlogBundle\DataFixtures\ORM\BlogFixtures::load() must be compatible with that of Doctrine\Common\DataFixtures\FixtureInterface::load() in src/Blogger/BlogBundle/DataFixtures/ORM/BlogFixtures.php on line 9
```

and 

```
Fatal error: Declaration of Blogger\BlogBundle\DataFixtures\ORM\CommentFixtures::load() must be compatible with that of Doctrine\Common\DataFixtures\FixtureInterface::load() in src/Blogger/BlogBundle/DataFixtures/ORM/CommentFixtures.php on line 10
```

All I've done in order to fix this issue was modification of this files:
`/src/Blogger/BlogBundle/DataFixtures/ORM/BlogFixtures.php`
`/src/Blogger/BlogBundle/DataFixtures/ORM/CommentFixtures.php`

in both files I've added:
`use Doctrine\Common\Persistence\ObjectManager;`

and changed method declaration:
`public function load($manager)`
to:
`public function load(ObjectManager $manager)`

Now it's working.

**Comment by jaimesuez** [comment]
this is fixed in the documentation
